### ISSUE TITLE
Italienisch: 'Geschäftsjahr' -> 'esercizio contabile'

### ISSUE THREAD

**Issue by s3lph** [cluck/statuten#4]
Disclaimer: I Am Not A Lawyer & mein Italienisch ist nicht gerade das beste.

> La chiusura dell'anno contabile cade [...] nel primo trimestre di tale anno contabile.

Wäre wahrscheinlich besser:

> La chiusura dell'**esercizio** contabile cade [...] nel primo trimestre di tale **esercizio** contabile.

Quelle: http://pluris-cedam.utetgiuridica.it/pdf/dizionario_multilingue_massari.pdf

**Comment by cluck** [comment]
indeed
