### ISSUE TITLE
CfP

### ISSUE THREAD

**Issue by s3lph** [cluck/statuten#5]
In den aktuellen deutschsprachigen Statuten:

>  [der **Call for Participation (CfP)** zur «Chaos Singularity (CoSin)» [...]

In der italienischen Version:

> La **«chiamata a partecipare»** al raduno «Chaos Singularity (CoSin)» [...]

Französisch:

> **«L’appel à participer»** au rassemblement «Chaos Singularity (CoSin)» [...]

Zumindest die Abkürzung 'CfP' sollte m.E. in den italienischen und französischen Statuten erwähnt sein. 

Macht es Sinn, "Call for Participation" in allen drei Sprachen auf Englisch zu verwenden (Stichwort Einheitlichkeit)? Ich kenne mich mit den beiden Sprachen zu wenig aus, um sagen zu können, ob und wann Anglizismen in diesen Sprachen Sinn machen.

**Comment by cluck** [comment]
Ich bin da auch unentschlossen. Dein Vorschlag das zu vereinheitlichen scheint mir vernünftig, und wenn da keine weitere Kommentare kommen übernehme ich das so.

Ich persönlich verschlucke mich halt am Begriff CfP ganz allgemein weil es nur akademiker lustig finden. Aber ändern können wir das jetzt nicht.
