### ISSUE TITLE
"Assemblée du Chaos" vs "Assemblée chaotique"

### ISSUE THREAD

**Issue by marvelous** [cluck/statuten#6]
Does "Chaosversammlung" mean "Chaotic Assembly" or "Assembly from the Chaos"?

**Comment by cluck** [comment]
I think the double meaning is actually part of the game :D

**Comment by marvelous** [comment]
Unfortunately, the double meaning doesn't translate into french. Then the question is: which one fits better?

**Comment by cluck** [comment]
Oh main non! Well then I suggest to stick to reality and prefer the latter, the "assemblement of the constitutents of 'the chaos'", to the former - the idea that the "assemblement" itself may show chaotic revolutions while it is taking place.
